### ISSUE TITLE
Unable to run segmenter.py

### ISSUE THREAD

**Issue by shaniAmare** [Psy-Fer/SquiggleKit#10]
Hi James,

Thank for the quick reply the other day. Now I'm using `segmenter.py` to see whether I can use the results for downstream `MotifSeq.py' .

I first used `bgzip` to compress the `.signal.csv` files from `squigglePull` and created `.gzip` files as below
`for file in ${out_dir}/squigglepull/*.data.csv` 
`do`
`bgzip < ${file} > ${file}.gzip`
`done`

Next, I used following command to run`segmenter.py` in `Python 2.7`
`for file in ${out_dir}/squigglepull/*.gzip` 
`do` 
`prefix=${file##*/}; prefix=${prefix%%.*};`
`python ${sourceFiles}/SquiggleKit-master/segmenter.py -s ${file} -ku -j 100 > ${out_dir}/squigglemotifseq/${prefix}_signals_stall_segments.tsv`
`done`

But, I'm getting the following error :
`Traceback (most recent call last):`
  `File "SourceFiles/SquiggleKit-master/segmenter.py", line 383, in <module>`
    `main()`
  `File "SourceFiles/SquiggleKit-master/segmenter.py", line 193, in main`
    `sig = np.array([int(i) for i in l[3:]], dtype=int)`
`ValueError: invalid literal for int() with base 10: 'all'`

Please tell me what I'm doing wrong here?

Thanks a lot,
Shani.

**Comment by Psy-Fer** [comment]
Hey,

Latest update of segmenter will fix this for now with your current output.

This is a temp fix till the latest update i'm working on comes out.

Let me know how that goes.

Cheers.

**Comment by shaniAmare** [comment]
Thanks James. It works now. So I will close this issue. However, I have raised a separate issue regarding `MotifSeq.py` in [#issue-438134930](https://github.com/Psy-Fer/SquiggleKit/issues/11#issue-438134930). Thanks a lot, Shani.
