### ISSUE TITLE
Unable to use SquigglePull to read event data

### ISSUE THREAD

**Issue by VidurangaWijekoon** [Psy-Fer/SquiggleKit#12]
Hello,

I just started using SquiggleKit, and am trying to use SquigglePull to read raw and event data in the fast5 files provided in the repository. Raw data are read as expected, but I cannot get it to read event data. I am getting the following error.

![image](https://user-images.githubusercontent.com/13881209/57755238-b417b200-7733-11e9-84a9-84d396338911.png)

I checked the code at the specified line, and it looks to me as if the error message is valid. But this is the first time I am using Python, so I am most probably wrong. My version of Python is 2.7.15rc1, and I am using the library on Ubuntu in Windows 10. 

Could someone please help me in getting the issue fixed? Thanks in advance!

**Comment by Psy-Fer** [comment]
Hello,

Ahh, yes I have not given the even extraction much care, as I was planning to remove it.

The problem was when I added the read_id extraction, I didn't port refrence
`c = hdf['Raw/Reads'].keys()`
to be able to find it in the event extraction logic.

I just did a quick little update.

Please do a `git pull` and try again.

Cheers, and thanks for using SquiggleKit

**Comment by Psy-Fer** [comment]
Hey there,

any news if that fix worked?

**Comment by VidurangaWijekoon** [comment]
Hi,

Thanks a lot for the fix. Just checked it out. It does give an output, but I am not sure whether the values are correct. I tested with the test.fast5 file provided with the repository, and for event extraction, did not use any optional commands. For raw data, I get values around 500, and for event data, they are around 100. I am not sure whether it is supposed to be like that.

I am attaching both the outputs for your reference.

[outputs.zip](https://github.com/Psy-Fer/SquiggleKit/files/3210729/outputs.zip)

**Comment by Psy-Fer** [comment]
Yes, that's correct.

The events are in a different range to the raw asic measurements.

So that is expected output.
