### ISSUE TITLE
Pull cell barcodes 

### ISSUE THREAD

**Issue by callumparr** [Psy-Fer/SquiggleKit#14]
Can squigglepull be used to de-multiplex using a tsv of cell barcodes generated by parallel HiSeq run?

**Comment by Psy-Fer** [comment]
Hello,

SquigglePull just extracts the signal data from fast5 files. 

If you are attempting to do single cell barcode demultiplexing using the signal data, and a white list from illumina, then that would be a job done with motifseq. However it may be trickier than it seems, as the cell barcodes are, for 10x, only 16nt long. 

A few people are currently working on this, including myself. So you can either wait for that, or have a crack yourself :)

Let me know if you want to know anything else. 

Regards 
James

**Comment by callumparr** [comment]
I will have a go but that seems a well beyond me. :) I
