### ISSUE TITLE
Erreur de segmentation (core dumped)

### ISSUE THREAD

**Issue by DelphIONe** [Psy-Fer/SquiggleKit#17]
Hi,

I try to use Squigglekit and after any command, I obtain the result AND this last line
Erreur de segmentation (core dumped)

Example below:
 python3 ~/softs/SquiggleKit/MotifSeq.py -s data.tsv --scrappie_model squiggle_r94 -i test_recherche_motif_1b.fasta > output_recherce_fin_1b_sans_signal

**********************************************************
*  z-score, p-value, probability, etc. are based on      *
*     preliminary experimental modeling only             *
*                Use at own risk                         *
**********************************************************

Erreur de segmentation (core dumped)

Can I trust in these results nevertheless ?
Thanks for your reply,

**Comment by Psy-Fer** [comment]
Hello,

I think you might be one of the first to use the new version of MotifSeq. 

Let me do some testing, and get back to you about the core dump.

The results should be fine. It's just not exiting correctly. I'll look into it.

James

**Comment by DelphIONe** [comment]
No problem, thanks for your reply :-)

**Comment by Psy-Fer** [comment]
Hmm, so I am getting the same problem with seg faults, even with just displaying the help

`python3 MotifSeq.py -h`

However, I don't get any seg faults with python2

This leads me to think it's a python2/3 library issue. i'll keep looking.

**Comment by Psy-Fer** [comment]
Hmm, when I comment out libraries one at a time, it goes away when I take out mlpy.

Time to investigate that. It's a troublesome library to begin with. I'm hoping I don't have to re-release it, but it would probably make it easier for everyone if I did. sigh...

**Comment by Psy-Fer** [comment]
okay! I have found a solution.

we can get rid of the manual install for python3 (still need it for python 2)

So, start of by clearing your mlpy from pip3

`pip3 uninstall mlpy`

run it twice just to make sure it gets everthing. depending on your system, you may have to use sudo.

Then do

`pip3 install machine-learning-py`

Then try again. This should remove the core dumps without any code change :)

Let me know how that goes.

**Comment by DelphIONe** [comment]
Hi,

I obtain with sudo pip3 uninstall mlpy
ERROR: Cannot uninstall 'mlpy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by Psy-Fer** [comment]
Hello.
Could you help me out by providing me with the following info?

How did you install mlpy the first time?
Which Operating system are you on?
What does your `pip3 freeze` say?

The instructions above are more for the general use, to be modified based on individual environment and circumstance. But I'm happy to help you get to the bottom of this problem, as your questions has already lead to an improvement in the kit. 

Thanks!

**Comment by DelphIONe** [comment]
Hi,

Sorry, I don't remember how I installed mlpy... I'm working on Ubuntu 16.04.
pip3 freeze output:
asn1crypto==0.24.0
attrs==19.1.0
Automat==0.7.0
cffi==1.12.3
chardet==2.3.0
command-not-found==0.3
constantly==15.1.0
cryptography==2.7
cssselect==1.0.3
cycler==0.10.0
decorator==4.4.0
h5py==2.6.0
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
kiwisolver==1.1.0
language-selector==0.1
lxml==4.3.4
matplotlib==3.0.3
mlpy==3.5.0
networkx==2.3
numpy==1.16.4
ont-albacore==2.3.3
ont-fast5-api==0.3.3
parsel==1.5.1
porechop==0.2.4
progressbar==2.3
pyasn1==0.4.5
pyasn1-modules==0.2.5
pycparser==2.19
pycurl==7.43.0
PyDispatcher==2.0.5
pygobject==3.20.0
PyHamcrest==1.9.0
pyOpenSSL==19.0.0
pyparsing==2.4.0
pysam==0.15.2
python-apt==1.1.0b1
python-dateutil==2.4.2
python-debian==0.1.27
python-systemd==231
queuelib==1.5.0
requests==2.9.1
scipy==1.3.0
scrappie==1.4.2
Scrapy==1.6.0
service-identity==18.1.0
six==1.10.0
ssh-import-id==5.5
svim==1.0.0
Twisted==19.2.1
ufw==0.35
unattended-upgrades==0.1
unicycler==0.4.3
urllib3==1.13.1
w3lib==1.20.0
zope.interface==4.6.0

I hope that helps you...

**Comment by Psy-Fer** [comment]
Hello,

Perhaps your solution can be found here

https://stackoverflow.com/questions/1550226/python-setup-py-uninstall

This is assuming you installed using something like `python3 setup.py install` in the mlpy download folder. Then you should be able to go about installing the new version with pip3

**Comment by Psy-Fer** [comment]
Hello @DelphIONe 

How did you go with this? have you been able to fix the problem?

Regards,
James.
