### ISSUE TITLE
Overlaying raw signal of particular target

### ISSUE THREAD

**Issue by callumparr** [Psy-Fer/SquiggleKit#18]
I was wondering how would I go about visualizing raw signal from multiple reads of a particular transcript for instance. 

SquigglePull with SquigglePlot I guess would be difficult as it's difficult to align the multiple reads at some particular point. 

SequenceMotif works for smaller sequences within a gene but not for visualizing an entire gene. 

So then how about first segmenter on reads identified to be the gene of interest to extract within stall and polyA and then plot the results.

Is there support to overlay signals in SqiggleKit?

**Comment by Psy-Fer** [comment]
Hello,

Currently there is no overlap method within SquiggleKit. I must admit, I skirted away from it a bit given tombo is pretty darn good at that. 

You have identified the correct reasons for why it's tricky. Aligning the squiggles up makes it tricky. Without doing, as tombo does, re-squiggle on the reads and aligning the squiggle with the reference, it's difficult to account for the noise of the reads and get a visualisation that actually yields useful information. 

There is perhaps a way to map the read to a gene and vice versa, to extract the signal, and then use the warping path to correct the squiggle to better match the synthetic. However that functionality does not currently exist. 

Is there a particular purpose to stacking squiggles? Perhaps I can help if I knew more. Feel free to email me if you don't wish to make it public 

Cheers
James

**Comment by callumparr** [comment]
Ah OK tombo maybe good for this. I was thinking of ways to show raw signal for a particular target for presentations and such just to get some idea. I give tombo another go.
