### ISSUE TITLE
finding specific kmers

### ISSUE THREAD

**Issue by avilella** [Psy-Fer/SquiggleKit#2]
Hi, I found out about SquiggleKit and I am trying to perform an analysis with the MotifSeq module.

Is it possible to plot/export the squiggles for a specific kmer after basecalling?

E.g. if the kmer was TACTGACTGCTA

Can I call squigglekit MotifSeq by building a `file.model` of my kmer without knowing what the squiggle should look like?

Apologies if this is explained somewhere, I couldn't find how to create the input files signals_stall_segments.tsv and adapter.model in this command in the documentation:

```
python MotifSeq.py -s signals.tsv.gz --segs signals_stall_segments.tsv -a adapter.model -t 120 -d 120 > signals_adapters.tsv
```

**Comment by argershman** [comment]
Also wondering this! I have tried simulating the kmer in scrappie but haven't gotten it to work

**Comment by Psy-Fer** [comment]
Ahh wonderful problem. I'm at a conference at the moment, but I'll hit this
in the next day or two.

**Comment by Psy-Fer** [comment]
I've updated the readme to include how to grab a kmer motif. It Will print out the position in the signal, which you can then use to slice out the raw signal from the signal file.

I'll chuck in a method of doing this into MotifSeq itself if that makes it easier. 
Also, the seg file is optional. Depends what you are looking for.

I'll get some of these changes done in the next day or so.

Thanks for the feedback :)

**Comment by Psy-Fer** [comment]
Hello,
I was just looking at scrappie, and it's had an update. 1.4  has column headers, 1.2 does not.
Going to fix that up, to take old and new versions of scrappie models.

Also, i'm going to make it easier to extract the signals, as well as the positions, kinda like a truncated SquigglePull output.

**Comment by Psy-Fer** [comment]
Okay, latest push has the argument -x that will dump the normalised current, as well as the start/end positions, and dynamic programming distance value and length.

Next, i'll add in a flag in the visualisation flag to plot the synthetic model signal with the found signal, so it's easy to confirm similarity by eye.

For more information, be sure to check out the full documentation at https://psy-fer.github.io/SquiggleKitDocs/ 

I'll close this issue, if that's solved the issues?

**Comment by Psy-Fer** [comment]
Hopefully that fixed it.
Closing issue
