### ISSUE TITLE
What does the scaled_mad mean?

### ISSUE THREAD

**Issue by youyupei** [Psy-Fer/SquiggleKit#20]
Hi James,
May I ask a question?
I noticed in your MotifSeq.py, when you doing the current normalization, why did you do this:
scaled_mad = mad * 1.4826??

**Comment by Psy-Fer** [comment]
Hey!

Yep, read this 
https://en.wikipedia.org/wiki/Median_absolute_deviation

You will find how the constant scale factor is calculated assuming a normal distribution. 

Let me know if that answers your question. 

James

**Comment by Psy-Fer** [comment]
This is the relevant section

![image](https://user-images.githubusercontent.com/8985577/64832218-55e4d800-d61c-11e9-890a-1d4684dc76cb.png)

I hope this helps!

James

**Comment by youyupei** [comment]
Got it! 
Thanks, James, and sorry for the late reply. It is really helpful!

**Comment by Psy-Fer** [comment]
Wonderful. Glad I could help.
