### ISSUE TITLE
SquigglePull command does not print help

### ISSUE THREAD

**Issue by splaisan** [Psy-Fer/SquiggleKit#22]
seems to have installed, finally.
Apparently python 7 does not like mlpy and python 3.6 on ly can install with pip and not with conda (sad as I do not like to pip too much.

What does SquigglePull.py do (_a dry run does not give me much info, is this normal?_)

```
/opt/biotools/miniconda3/envs/base3.6/bin/python /opt/biotools/SquiggleKit/SquigglePull.py -h
  File "/opt/biotools/SquiggleKit/SquigglePull.py", line 139
    print '{}\t{}\t{}\t{}\t{}'.format(
                             ^
SyntaxError: invalid syntax
```

a real command also fails

```
/opt/biotools/miniconda3/envs/base3.6/bin/python /opt/biotools/SquiggleKit/SquigglePull.py reads/0/ -f all > test.tsv
  File "/opt/biotools/SquiggleKit/SquigglePull.py", line 139
    print '{}\t{}\t{}\t{}\t{}'.format(
                             ^
SyntaxError: invalid syntax
```

other commands show help on dry run or --help

**Comment by Psy-Fer** [comment]
Hello.

Sorry, i've been away for the last week. I'll get back to you as soon as i've cleared off some urgent matters now i'm back at work.

Talk soon.
James

**Comment by Psy-Fer** [comment]
Hi,

So the issue here, is I have yet to upgrade SquigglePull to work with python3.
That print statement wont work in python3. 

It's coming in the next update. Sorry for the current inconvenience.

**Comment by splaisan** [comment]
OK, I'll try to progress on other fronts meanwhile.
thanks for the nice tools
