### ISSUE TITLE
MotifSeq seg faulting at read_bait_model

### ISSUE THREAD

**Issue by 690645258** [Psy-Fer/SquiggleKit#25]
Hi again,

I'm trying to run MotifSeq on my newly acquired SquigglePull data (thanks again for fixing that!) but I keep on getting the following error message:

`Traceback (most recent call last):
  File "/home/user/tools/SquiggleKit/MotifSeq.py", line 520, in <module>
    main()
  File "/home/user/tools/SquiggleKit/MotifSeq.py", line 153, in main
    model, m_order, L = read_bait_model(args.model)
  File "/home/user/tools/SquiggleKit/MotifSeq.py", line 420, in read_bait_model
    L = int(l[1])
IndexError: list index out of range
Segmentation fault (core dumped)
`

The command to run this was:

`python3.6 /home/user/tools/SquiggleKit/MotifSeq.py -s ./output.tsv -m ./kmer.model`

I've used scrappy on both my motif of interest and also with your example from Squigglekit read the docs and both times I get the same error.

The output from scrappy squiggle using your example fasta is the following which I'm hoping is the right output for MotifSeq? 

`#my_kmer_name

pos	base	current	sd	dwell

0	A	-0.431606	0.380354	1.058162

1	T	1.166496	0.338997	1.447607

2	C	0.450231	0.156083	4.044586

3	G	-1.232723	0.151543	5.830419

4	A	-1.257596	0.212146	4.654805

5	T	1.789353	0.239968	6.895236

6	C	0.315072	0.139455	7.184886

7	G	-0.477836	0.110022	8.183088

8	C	0.513699	0.117384	8.406736

9	T	0.918025	0.182820	6.356708

10	A	-0.463172	0.136564	6.415285

11	T	1.280751	0.209826	7.606201

12	G	-0.146407	0.107954	6.591394

13	C	0.483716	0.102067	7.065899

14	T	0.864263	0.165668	7.642580

15	A	-0.401214	0.111559	8.543694

16	G	-0.268080	0.108424	9.368885

17	C	0.405020	0.162891	8.274393

18	A	-0.954562	0.178741	7.976818

19	T	0.782907	0.137494	8.567830

20	T	0.708146	0.162590	8.998590

21	A	0.187392	0.135081	9.264595

22	C	0.513184	0.291414	17.157631

23	G	-0.532910	0.667264	14.425996`

(Edited the above to put a line of whitespace inbetween each row for readability's sake, turns into a paragraph otherwise, also attached an actual copy, real one doesn't include the .txt)
[adapter.model.txt](https://github.com/Psy-Fer/SquiggleKit/files/3875126/adapter.model.txt)

**Comment by Psy-Fer** [comment]
Hello again,

Do a quick look at -h on motifseq, and you find I've built scrappie into motifseq now, so you can just parse a fasta file and it will build the model for you. Options -i and the scrappie model option. 

Also, make sure you are using the latest version, 1.3.0

Let me know how that goes, I am on my phone at the moment and can give more support when back at work :) 

Jamss

**Comment by 690645258** [comment]
Just tested it and is running nicely with the included scrappie!

Think I must have missed that option since I'd just been relying on the SquiggleKit docs page and looks like that might have not have gotten updated with that change [relevant page](https://psy-fer.github.io/SquiggleKitDocs/MotifSeq/).

Thanks again for the prompt help!

**Comment by Psy-Fer** [comment]
Great!

yea, I will update the docs and more of the code when I get a chance.
I've been busy with another project that has taken me away from this one, but always happy to give quick support when needed.

Closing this ticket.
