### ISSUE TITLE
Match output to fast5s

### ISSUE THREAD

**Issue by gmoneyomics** [Psy-Fer/SquiggleKit#3]
Hi. I have been running MotifSeq.py to look for specific kmers in my fast5 files, but how do I match the output from these to the filenames or read IDs (either one) of my fast5s?

**Comment by Psy-Fer** [comment]
Hello, and thanks for using SquiggleKit.

Yes, you are right. I recently added a `-x` mode which extracts the normalised signal of the match, which also includes the fast5 file name, but the other outputs didn't include it.

I just updated those outputs to include the fast5 filenames.

Just go to the repo folder and do a `git pull` and it should update to the latest.

Let me know how it goes.

**Comment by Psy-Fer** [comment]
Hopefully that helped. There will be ReadIDs included in the next release.
Closing issue.

**Comment by gmoneyomics** [comment]
Thank you! It worked great!

**Comment by Psy-Fer** [comment]
No worries. Thanks for raising the issue.
