### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

### ISSUE THREAD

**Issue by harisankarsadasivan** [Psy-Fer/SquiggleKit#33]
I'm getting this error when i run motifseq

**Comment by Psy-Fer** [comment]
Well that's interesting.

Could you please show me the command you are running?
Also please do a `pip feeze` or `pip3 freeze` depending on your setup
As well as a `python --version` for the version of python you are using.

Thanks

**Comment by Psy-Fer** [comment]
Also can you please let me know which operating system this is on?
Thanks
