### ISSUE TITLE
Python3 SquiggleKit

### ISSUE THREAD

**Issue by XPHenry** [Psy-Fer/SquiggleKit#37]
Hi,
I was just wondering if it was possible to 'push' the python3 version anytime soon.
Thanks a lot

**Comment by Psy-Fer** [comment]
Hello,

Most of the tools do work with python3 already.
Is there a particular tool that isn't working for you? i'll fix it for you ASAP if that is the case.

Regards,
James

**Comment by XPHenry** [comment]
Hi, I used the tools and it was errors from my end, you were right they work on python3.
Sorry for bothering
