### ISSUE TITLE
Unable to run MotifSeq.py

### ISSUE THREAD

**Issue by FlorianBrnrd** [Psy-Fer/SquiggleKit#4]
Hi, I'm trying to use squiggleKit to identify a sequence at the beginning of my reads but for some reason I am unable to run correctly MotifSeq.py when all the other scripts work correctly.

I tried to run it with that command:

`python2 MotifSeq.py -p /Users/florian/Desktop/test -m SL1_kmer.model -v`

And I got that error for every fast5 in my test folder:

```
Traceback (most recent call last):
  File "MotifSeq.py", line 275, in process_fast5
    b = sorted([i for i in hdf['Analyses'].keys() if i[0] == 'B'])[-1]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Analyses' doesn't exist)"
```
I am on MacOS X 10.13.6 (High Sierra) and I believe all the dependencies are up to date. 

I also tried to use other set of fast5 files coming from another run but the error remained.
I thank you in advance for any help.

Florian

**Comment by Psy-Fer** [comment]
Hello Florian,

Thanks so much for picking that up. That is a bug I must have missed during my testing left over from legacy code.
I have removed the offending line, and updated the repo.

Simply do a `git pull` in the folder or download MotifSeq.py again, and the issue should be fixed.

Let me know if this works
Cheers,
James F.

**Comment by Psy-Fer** [comment]
I'm going to assume this is fixed.

Closing for now.

**Comment by FlorianBrnrd** [comment]
Hi,
Sorry for the delay, I was attending a conference and didn't have time to check if it was working or not. I just had a test and now it's working okay so thanks a lot ! I had managed to visualize some read's signal by generating a .tsv file with SquigglePull but directly using the fast5 file is much better !

I also have some questions regarding how to use SquiggleKit to its full extent, should I open up another "issue" or could I maybe email you directly ?

Thanks for your time and reactivity.

**Comment by Psy-Fer** [comment]
Hi
If it's something like a bug or odd functionality, feel free with throw up another issue.
If it's just how to use it on something particular, shoot me an email
j.ferguson@garvan.org.au
