### ISSUE TITLE
dRNA_segmenter read_dic 

### ISSUE THREAD

**Issue by smaegol** [Psy-Fer/SquiggleKit#40]
Hi,

when trying to run dRNA_segmenter.py I got this:

```
Traceback (most recent call last):
  File "./dRNA_segmenter.py", line 137, in <module>
    main()
  File "./dRNA_segmenter.py", line 126, in main
    print "{}\t{}\t{}\t{}".format(f5, read_dic[f5], x, y)
NameError: global name 'read_dic' is not defined

```

Any solutions? Seems like variable declaration is missing somewhere

**Comment by Psy-Fer** [comment]
Hello Pawel,

Looking at this now.

Get back to you soon.
James

**Comment by Psy-Fer** [comment]
Ahh, seems like I stuffed up when I pulled this out from reading fast5s directly, to reading a squigglePull signal file.

That should be fixed now, whee the signal file columns are: fast5_fileneame, readID, whatever..., signal......

Also, if you want to read from fast5 files directly, you can use the sub-module in DeePlexiCon, "squig" --segment. Same algorithm.

https://github.com/Psy-Fer/deeplexicon

Let me know if you have any other issues :) 

James
