### ISSUE TITLE
Issue with h5py

### ISSUE THREAD

**Issue by XPHenry** [Psy-Fer/SquiggleKit#41]
Hi, I'm trying to use SquigglePlot for a multi fast5 file that was generated recently, with the following command:
`python ../SquiggleKit/SquigglePlot.py -i test/FAO01221_pass_d7290dd7_0.fast5 
`

 but this error comes out:

```
/home/henrik/miniconda3/lib/python3.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "../SquiggleKit/SquigglePlot.py", line 327, in process_fast5
    c = list(hdf['Raw/Reads'].keys())
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/henrik/miniconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 169, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (Incorrect metadatda checksum after all read attempts)'
process_fast5():failed to extract events or fastq from: test/FAO01221_pass_d7290dd7_0.fast5main():data not extracted: test/FAO01221_pass_d7290dd7_0.fast5
```
And SquigglePull encounters the same problem as well, both with python2 and python3. The same command works just fine with previous fast5 files, probably dating back to a few months.

Do you think there is a solution to this?
Thank you,
Henry

**Comment by Psy-Fer** [comment]
Hello Henry,

That looks like you are inputting a multi-fast5 file?
in that case, please use `-m` or `--multi` to set it to read multi-fast5 files.
You can set the particular readID you wish to look at if you like with `-r` otherwise it will just cycle through each one.

If it's a single fast5 file, then it's probably to do with utf-8 encoding, which I can fix, though single files are not really used anymore except in special circumstances.

Let me know :) 

James

**Comment by XPHenry** [comment]
It was a multi fast5 but even with the -m it gave the same error.
Although it seemed to work on some other files from the same run, so it might be just a corrupted file.

In any case I don't think the bug is coming from SquiggleKit, and thank you with your help.

Cheers,
Henry

**Comment by Psy-Fer** [comment]
That is indeed strange.
Have you tried opening the file with HDF View? ( https://www.hdfgroup.org/downloads/hdfview/ )

fast5 files are just hdf5 files, and the viewer may be able to see if there is an issue with a particular read, or the whole file.

Anyway, glad it works for your other data.
