### ISSUE TITLE
squigglepull scale and pA_convert functions does not work with multifast5 files

### ISSUE THREAD

**Issue by Akanksha2511** [Psy-Fer/SquiggleKit#47]
Hi James, 

Just wondering if the scale and pA_convert functions in squigglepull are not yet available for multi fast5 files?

Thanks, 
Akanksha

**Comment by Psy-Fer** [comment]
Hello Akanksha,

It seems you are right. How lazy of me.
Would you like me to update that for you?

James

**Comment by Akanksha2511** [comment]
Hi James, 

could you please update it.

Thanks,
Akanksha

**Comment by Psy-Fer** [comment]
Hello Akanksha.

The latest commit to SquigglePull should add both pA_convert and scale (z-scaling or med-mad scaling) to the outputs for multi-fast5 files.

Let me know if there are any issues.

James

**Comment by Akanksha2511** [comment]
Thanks, James. I am getting an error saying "
    for i in pA_sig:
TypeError: 'int' object is not iterable". Command I am giving is 
python SquigglePull.py --multi  -c  -p

**Comment by Psy-Fer** [comment]
Ahh that was my bad.

Please pull the latest change and try again. Should work this time.

**Comment by Akanksha2511** [comment]
Awesome. Thanks for the quick response, James

**Comment by Akanksha2511** [comment]
Hi James, 

Sorry to bother you but I get the same error as before if I use both -s and -c options. 

The error says 

  for i in pA_sig:
TypeError: 'int' object is not iterable

Thanks, 
Akanksha

**Comment by Psy-Fer** [comment]
Hello Akanksha,

Sorry about that. There was an issue with numpy translating float vs int. That should be fixed now.

I would suggest caution scaling already pA converted data. But it's very use case dependant.

Let me know if you have any other troubles.

James
