### ISSUE TITLE
Unable to run SquigglePull.py

### ISSUE THREAD

**Issue by curt-f** [Psy-Fer/SquiggleKit#5]
I obtained some (not very good) data with a minION 9.4.1 flow cell and would like to look at the squiggle of my longest read.  

Here is what I tried:

`(squiggle) [curtf@smsx10srw-srcf-d15-37 first_arabidopsis_run]$ python ~/sw/squiggle_kit/SquigglePull.py -rv -p fast5 -f all`

For every `*.fast5` file in the `fast5/` directory, I got the following error message:

```
Traceback (most recent call last):
  File "/home/curtf/sw/squiggle_kit/SquigglePull.py", line 202, in extract_f5
    c = hdf['Raw/Reads'].keys()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/curtf/miniconda3/envs/squiggle/lib/python2.7/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'
extract_fast5():failed to extract events or fastq from fast5/FAK46075_43956a1747a03d24c1eed090b017e3af2034cf55_18.fast5
main():data not extracted. Moving to next file
```
From manually browsing (with HDFCompass) some of the `*.fast5` files that I have, it seems they have a different structure than what the SquiggleKit code expects.  Instead of any `Reads` group, the `Raw` group in my `*.fast5` files each has a single sub-group called `Signal`.  I'm attaching a screenshot of HDFCompass for one fast5 file I have, showing this structure.

![Screen Shot 2019-03-18 at 09 19 29 ](https://user-images.githubusercontent.com/36312929/54545570-27cd5680-495f-11e9-8c44-77a5dcb9df37.png)

Did I do something wrong or is the fast5 output from the latest MinKnow somehow different than what is expected?

**Comment by nodrogluap** [comment]
Hi,

Are you running Python3?  I ran into the same issue because of changes in how arrays and lists work in the language.  This fixes it:

c = list(hdf['Raw/Reads'].keys())

I'm generating a fork and will make a pull request as there are a number of other subtle changes that need to be made to support Python 3 (with backward compatibility I think) and newer numpys.

**Comment by curt-f** [comment]
Hmm, I thought I'd made a Python 2 conda env and also thought I used it at the time.  But I'll have to check again; it looks like you might be on to something.

**Comment by curt-f** [comment]
I can now confirm I *am* running Python `2.7.16.`

```
(squiggle) [curtf@smsx10srw-srcf-d15-37 first_arabidopsis_run]$ python --version
Python 2.7.16 :: Anaconda, Inc.
```

**Comment by Psy-Fer** [comment]
Hello
Thanks for using SquiggleKit!

Is that fast5 from a multi fast5 by any chance?
I had some new runs on just recently, so i'll grab some of the files from the great wall of NAS and have a look at their structure.

get back to you shortly

**Comment by Psy-Fer** [comment]
Ahh yes, so looking at the conversion methods from ONT for multi_fast5 to single, the read number section is no longer used.

```
 if group == "Raw":
    read_number = read.handle["Raw"].attrs["read_number"]
    single_f5.handle.copy(read.handle[group], "Raw/Reads/Read_{}".format(read_number))
```
They do however add it back in when converting from multi to single.

The short fix for this, would be to run the multi_to_single_fast5 method from this repo 
https://github.com/nanoporetech/ont_fast5_api 

Then try again.

Python 3 as well as multi-fast5 support is coming in the next update, while still maintaining backwards compatibility to R9.4 single fast5 files.

**Comment by curt-f** [comment]
Thanks for making SquiggleKit!  It is a great tool and I'm likely to use it extensively in the coming months.

My individual `*.fast5` files each contain 4000 reads.  My (not very good) run generated 30-ish of these files.  They weren't compressed and were available as individual `*.fast5` files after   This value is a parameter set in MinKNOW at run time, but 4,000 was the default value IIRC.  As this was my first run, I'm not entirely sure if this behavior of MinKNOW and the resulting file structure is different than what it's been in the past, or if I'm just doing something crazy.  

Maybe I need to use `multi_to_single_fast5` from [this tookit](multi_to_single_fast5) and try again?

**Comment by Psy-Fer** [comment]
Indeed, Using `multi_to_single_fast5` will solve this issue for now.

I've got a few people bugging me for multi_fast5 file support (ie, many reads in 1 fast5 file). So it's high on my TODO list.

**Comment by Psy-Fer** [comment]
Hey @curt-f how did you get on with the multi to single conversion?

**Comment by curt-f** [comment]
Sorry, just trying this now...

**Comment by curt-f** [comment]
I was able to run the conversion fine, resulting in many many fast5 files.  And when I pick a random one and try to do SquigglePull on it, it runs, but doesn't output anything.

```
(squiggle) [curtf@smsx10srw-srcf-d15-35 ~]$ python ~/sw/squiggle_kit/SquigglePull.py -rv -p ~/data/first_arabidopsis_run/single_fast5/0/96952511-08a4-4b59-a752-8ebd52114c70.fast5 -f all
Verbose mode on. Starting timer
Time taken: 0.00177311897278
(squiggle) [curtf@smsx10srw-srcf-d15-35 ~]$ 
```

This seems like a different issue, and maybe (probably) just something silly I am doing.

**Comment by Psy-Fer** [comment]
Hello Curt,

The -p command is for a top path, to run through all fast5 files.
if you wish to access a specific file, please chuck it into its own folder and point at it.
update coming to the same versatility to SquigglePull as fast5_fetcher.

**Comment by Psy-Fer** [comment]
This should now be fixed with the release of `fast5_fetcher_multi.py`.

It will go from multi to single with this first release.

**Comment by Psy-Fer** [comment]
Hello Curt,
SquigglePull now supports multi-fast5 files using the `--multi` argument.
James
