### ISSUE TITLE
SquigglePlot.py with -n 20 option produces more than one plot

### ISSUE THREAD

**Issue by waltergallegog** [Psy-Fer/SquiggleKit#53]
Hello,
I'm following your [tutorial](https://psy-fer.github.io/SquiggleKitDocs/SquigglePlot/) and wanted to plot a .fast5 I got from [here](s3.amazonaws.com/nanopore-human-wgs/rna/Multi_Fast5/Chip137_IVT_NA12878_Data_reads/Chip137_IVT_NA12878_Data_reads_0.fast5), given that the one under the examples folder was giving me an error (same as [issue 51](https://github.com/Psy-Fer/SquiggleKit/issues/51) )

I used the `-n NUM`option, which if I understood correctly should plot only the first `NUM` data points.
However what I observed is that multiple plots of size `NUM` are generated.

Same behavior observed if using `-n START,FINISH` or the save options.
Is this the intended behavior?
Any way to limit to just one plot?

Some of the commands I used:

`python SquigglePlot.py -i ../datasets/Chip137_IVT_NA12878_Data_reads_0.fast5  -n 20`
Generates a plot window with 20 datapoints. As soon as I close it, a new one opens, with different data ( I suppose the next 20 points).
I assume it would continue to generate new plots until reaching the end of the file ( I closed maybe 15 windows, then just killed the process)

`python SquigglePlot.py -i ../datasets/Chip137_IVT_NA12878_Data_reads_0.fast5  -n 40,50`
Generates a plot window with 10 datapoints. As soon as I close it, a new one opens, with different data ( I suppose points 50,60)

`python SquigglePlot.py -i ../datasets/Chip137_IVT_NA12878_Data_reads_0.fast5  -n 20 --dpi 300 --no_show --save test.pdf --save_path example/pngs20`
Generates a bunch of pdf files, each with a graph of 20 datapoints.

Thanks
Walter

**Comment by Psy-Fer** [comment]
Hello,

It's not the NEXT 20 datapoints, it's the 20 datapoints of the next read in the multifast5 file.

If you wish to limit which read is being analysed, you can use the `--readID` flag to say which read.

I hope that helps

**Comment by waltergallegog** [comment]
Hello,
I didn't realized it was a multfast5 file. Thanks for the quick response and sorry for the trouble.
Walter

**Comment by Psy-Fer** [comment]
All good :) let me know if you have any other questions or something isn't working how you want it to.

James
