### ISSUE TITLE
Plotting specific readID from slow5 or blow5 file can take a long time

### ISSUE THREAD

**Issue by waltergallegog** [Psy-Fer/SquiggleKit#54]
Hello,
I'm learning how to use slow5 and blow5 formats.
I have a fast5 file which I have converted to slow5 and blow5 formats using slow5tools, with a command like:
`slow5tools f2s Chip137_IVT_NA12878_Data_reads_0.fast5 -o Chip137_IVT_NA12878_Data_reads_0.blow5 -p 8 -a`
`slow5tools index Chip137_IVT_NA12878_Data_reads_0.blow5`

readID `001bff3d-2e77-4be8-9e85-46cd7e05b7e0` is the first readID on the files
readID `fffc9fc5-69ba-4d51-a0ea-4fbaafb86276` is the last readID on the files.

Then I'm using SquigglePlot. This is what I have noticed:

- If I use the original `.fast5 `file and the **first** readID of the file, the plot is done immediately. If I close the plot, the program ends immediately (prints `Done`)
`python SquigglePlot.py -i Chip137_IVT_NA12878_Data_reads_0.fast5 -n 200 -r 001bff3d-2e77-4be8-9e85-46cd7e05b7e0`

- If I use the original` .fast5` file and the **last** readID of the file, the plot is done immediately. If I close the plot, the program ends immediately (prints `Done`)
`python SquigglePlot.py -i Chip137_IVT_NA12878_Data_reads_0.fast5 -n 200 -r fffc9fc5-69ba-4d51-a0ea-4fbaafb86276`

- If I use the `.blow5` file and the **first** readID of the file, the plot is done immediately. If I close the plot, the program takes a long time to close (to print `Done`).
`python SquigglePlot.py -w Chip137_IVT_NA12878_Data_reads_0.blow5 -n 200 -r 001bff3d-2e77-4be8-9e85-46cd7e05b7e0`

- If I use the `.blow5` file and the **last** readID of the file, the program takes a long time to produce the plot. If I close the plot, the program ends immediately (prints `Done`)
`python SquigglePlot.py -w Chip137_IVT_NA12878_Data_reads_0.blow5 -n 200 -r fffc9fc5-69ba-4d51-a0ea-4fbaafb86276`

With "a long time" I mean around 5 minutes. During the 5 minutes, the process uses 100% of one of the cpu cores.
The files have 4000 reads, and the original fast5 can be downloaded from [here](http://s3.amazonaws.com/nanopore-human-wgs/rna/Multi_Fast5/Chip137_IVT_NA12878_Data_reads/Chip137_IVT_NA12878_Data_reads_0.fast5)

Thanks for your support,
Walter.

**Comment by Psy-Fer** [comment]
Hey,

Yea I think I know what's causing that.
Could you please confirm which pyslow5 version you are running just to be sure?

I'll fix this up in squiggle plot.

James

**Comment by waltergallegog** [comment]
I'm running pyslow5 version 0.3.0
Walter

**Comment by Psy-Fer** [comment]
Hey Walter,

I've pushed an update to SquigglePlot. You should see a difference in performance now when using slow5.

I was a bit lazy in my initial integration of slow5 and was meant to come back to it. So thanks for making me fix that up.

You should be able to run the same commands now and see a vast improvement.

Cheers,
James

**Comment by waltergallegog** [comment]
Hey James,
Thanks for the quick fix, I have just tested and as you said, there is a vast improvement. The behavior with slow5 files is now similar to what I observed with .fast5 files.
Regards,
Walter
