### ISSUE TITLE
Running into issues with SquigglePlot.py using fast5 files converted from pod5

### ISSUE THREAD

**Issue by yinyuanmtu** [Psy-Fer/SquiggleKit#65]
Is there a way to make it work with the these converted fast5 files? Thanks!

**Comment by Psy-Fer** [comment]
Hello,

Try using blue-crab to convert pod5 to slow5 instead.

Fast5 was modified too many times by ONT to be stable for ongoing support.

Cheers,
James

**Comment by yinyuanmtu** [comment]
Hi James,
Thanks!
Does SquigglePlot.py take slow5 files or slow5 files need to be converted
to fast5 files in order to run SquigglePlot?
Thanks,
Yinan

Yinan Yuan, PhD
Assistant Professor in Forest Tree Genetics, Genomics and Biotechnology
College of Forest Resources and Environmental Science
Michigan Technological University
Phone: 906-487-1835

**Comment by Psy-Fer** [comment]
Hello,

squigglePlot can take slow5/blow5 files directly 

In the help of the script under  "-w", "--slow5",

James

**Comment by yinyuanmtu** [comment]
Great to know! Thanks alot James!
Yinan Yuan, PhD
Assistant Professor in Forest Tree Genetics, Genomics and Biotechnology
College of Forest Resources and Environmental Science
Michigan Technological University
Phone: 906-487-1835

**Comment by yinyuanmtu** [comment]
Hi James,
Just let you know that with blow5 files, the squigglePlot worked perfectly.
Thanks for all the help!
Yinan

Yinan Yuan, PhD
Assistant Professor in Forest Tree Genetics, Genomics and Biotechnology
College of Forest Resources and Environmental Science
Michigan Technological University
Phone: 906-487-1835

**Comment by Psy-Fer** [comment]
Great to hear.

Let me know if you need anything 🤓

James
