### ISSUE TITLE
"Syntax error near unexpected token" when using fast5_fetcher.py

### ISSUE THREAD

**Issue by FlorianBrnrd** [Psy-Fer/SquiggleKit#7]
Hi,

I don't know if this is a bug but I was trying to extract some raw signal files corresponding to a fastq file with 4k reads in it and it thrown me an error:

I used this command:

```
python2 fast5_fetcher.py -q /Users/florian/Bioinfo/fastq_runid_7f543cf3cc1afde81b9761e0789b9d792f3188c3_50.fastq -s /Users/florian/Bioinfo/run18_sequencing_summary.txt -i /Users/florian/Bioinfo/run18.index -o /Users/florian/Bioinfo/run18_fetch
```

and got that error:
```
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `cp /Users/florian/Bioinfo/Sequencing data/run18_raw_signal_data/reads/fast5(partie1)/8/worm_local_iecb_u_bordeaux_fr_20190221_FAK38838_MN24666_sequencing_run_cDNA_polyA_nll_kit_86332_read_1712_ch_118_strand.fast5 /Users/florian/Bioinfo/Sequencing data/run18_fetch'
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `cp /Users/florian/Bioinfo/Sequencing data/run18_raw_signal_data/reads/fast5(partie1)/8/worm_local_iecb_u_bordeaux_fr_20190221_FAK38838_MN24666_sequencing_run_cDNA_polyA_nll_kit_86332_read_1713_ch_316_strand.fast5 /Users/florian/Bioinfo/Sequencing data/run18_fetch'
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `cp /Users/florian/Bioinfo/Sequencing data/run18_raw_signal_data/reads/fast5(partie1)/8/worm_local_iecb_u_bordeaux_fr_20190221_FAK38838_MN24666_sequencing_run_cDNA_polyA_nll_kit_86332_read_1714_ch_91_strand.fast5 /Users/florian/Bioinfo/Sequencing data/run18_fetch'
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `cp /Users/florian/Bioinfo/Sequencing data/run18_raw_signal_data/reads/fast5(partie1)/8/worm_local_iecb_u_bordeaux_fr_20190221_FAK38838_MN24666_sequencing_run_cDNA_polyA_nll_kit_86332_read_1715_ch_431_strand.fast5 /Users/florian/Bioinfo/Sequencing data/run18_fetch'
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `cp /Users/florian/Bioinfo/Sequencing data/run18_raw_signal_data/reads/fast5(partie1)/8/worm_local_iecb_u_bordeaux_fr_20190221_FAK38838_MN24666_sequencing_run_cDNA_polyA_nll_kit_86332_read_1716_ch_79_strand.fast5 /Users/florian/Bioinfo/Sequencing data/run18_fetch'
```
I'm just putting a few lines but it's the same for every record it tries to fetch.

The reason why I'm not sure if this is really a bug is because I managed to make it work once (about 2 weeks ago) when I was trying Squigglekit to fetch about 360k raw signal files. But now I can't make it work anymore and it always throw me the same error. I even tried to reproduce the only time it worked for me, using the same files, but this time it returned the error.. 
But also, maybe there was an update that incorporated a bug in the meantime ? And I'm not sure how to download the previous version to test it out.

also, I checked the path to access the raw signal files and it seems good so the problem shouldn't come from a wrong index file (but maybe I missed something ?). 

It was kinda urgent so I managed to write a small python script myself to get the 4k raw signal files I needed but it took 1h and I know your script is way much more efficient so it would be nice if I could make it work for next time :)

I'm running python 2.7 on a Mac OS X 10.13.6  and I'm happy to provide any other informations if needed !

Thanks a lot.
Florian.

**Comment by Psy-Fer** [comment]
Gday,
I'll have a quick look and see if I can figure it out for you.

Looking at that, it seems it doesn't like the () brackets in the path name `fast5(partie1)` 

To test, try copy/pasting the cp command in the error there, and see if it works.
I'd hazard a guess it will complain, in which case renaming the folder to remove the brackets, and then regenerating the index file again (or use sed to replace the text to whatever you changed the folder to), and it should work.

I'll double check the cp code to make sure.

**Comment by Psy-Fer** [comment]
Hmm, looking at the changes, only comments were added/modified throughout the code.

I ran some tests anyway. Seems to be working on my end.
Have a go at the suggestions above, and let me know how you get on.

**Comment by FlorianBrnrd** [comment]
Hi, 
Thanks for the suggestions! The problem was indeed about 'special characters' like the parenthesis but there was also a whitespace in the folder name that was not properly escaped when the index was created (no backslash before). I resolved it by removing parenthesis and whitespace and now everything is working again !

Thanks a lot for your quick and efficient help and sorry for the rookie mistake !

**Comment by Psy-Fer** [comment]
No worries. I'll make a note of it in the documentation.
Perhaps create a troubleshooting section for stuff like this.

Thanks for your active feedback and use.
