### ISSUE TITLE
convert squigglePull output back to fast5

### ISSUE THREAD

**Issue by noncodo** [Psy-Fer/SquiggleKit#8]
A nice feature would be to convert _SquiggplePull_ output (e.g. .tsv files) back into a .fast5 format, with the option of selecting which metadata are kept. This would be akin to something like [PicoPore](https://github.com/scottgigante/picopore) or [f5pack](http://simpsonlab.github.io/2017/02/27/packing_fast5), but directly compatible with this toolkit.

**Comment by Psy-Fer** [comment]
That's good point. It would also allow for the splitting or merging of concatomers or incorrectly split reads (like what is seen in BulkVis).

I'd probably need the original fast5 files present to grab the meta data needed.

**Comment by Psy-Fer** [comment]
This has been handled by https://github.com/hasindu2008/slow5tools
